---
title: "Applied Practice"
author: "Emanuel Mejía"
date: "Week 5"
output: pdf_document
---

# 1. Safety First through Statistics
Suppose the strength of a particular metal beam is given by,
$$S = 5 + 2T^2 \cdot P$$
Where $T$ is a random variable representing the forging temperature and $P$ is a random variable representing purity. Suppose the following statements are true about these random variables:

- $T$ has a uniform distribution on $[0, 2]$.
- Conditional on a value for $T$, $P$ is has a normal distribution with mean $T/2$ and standard deviation $T/12$.

For example, if $T = 1$, then,
$$E[P|T = 1] = \frac{1}{2}$$
and,
$$\sigma[P|T = 1] = \sqrt{V[P|T = 1]} = \frac{1}{12}$$
1. Compute the expectation of $S$.

## *Solution*

Since $S = 5 + 2T^2P$, we know:

$$E[S] = E[5 + 2T^2P] = 5+2E[T^2P]$$

Now, to calculate $E[T^2P]$ we'll use the law of iterated expectations as follows:

\begin{align*}
    E[T^2P] &= E_T[E[T^2P|T]]\\
    &= \int_{-\infty}^{\infty}\left(\int_{-\infty}^{\infty} t^2p f_{P|T}(p|t)dp\right) f_T(t)dt\\
    &= \int_{-\infty}^{\infty}t^2\left(E[P|T = t]\right) f_T(t)dt\\
    &= \int_{-\infty}^{\infty}t^2\left(\frac{t}{2}\right) f_T(t)dt\\
    &= \frac{1}{2}\int_{-\infty}^{\infty}t^3 f_T(t)dt\\
    &= \frac{1}{2}\int_{0}^{2}t^3 (\frac{1}{2})dt & \text {Since } T \sim U(0,2)\\
    &= \frac{1}{4}\left[\frac{t^4}{4}\right]_0^2\\
    &= \frac{1}{4}\left[4\right]\\
    &= 1\\
\end{align*}

Substituting this back in our result for $E[S]$ we have that:

\begin{align*}
    E[S] &= 5+2E[T^2P]\\
    &= 5+2(1)\\
    &= 7
\end{align*}